[versions]
junit-jupiter = "5.10.0"
guava = "33.3.1-jre"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }


junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[bundles]
